version: "3.7"

services:

#  vue-app:
#    build:
#      context: tcm_frontend
#      dockerfile: Dockerfile
#    container_name: vue-app
#    restart: always
#    ports:
#      - "8080:8080"
#    networks:
#      - vue-network

  user_db:
    image: "fpirazzoli/sap_spe_db:latest"
    container_name: user_db
    restart: always
    ports:
      - "8082:8082"
      - "9092:9092"

  spring-db-app:
    build:
      context: src/main/userContext
      dockerfile: Dockerfile
    container_name: spring-db-app
    restart: always
    ports:
      - "9085:9085"

    #Per aggiungere un nuovo servizio
  #Seguire il template:

  #nome-servizio:
    #image:
    #ports:
    #container-name:
    # ecc.. ecc... (cambia a seconda delle necessità ma questi 3 sono quasi sempre obbligatori).

  #Eseguire il comando "docker compose up" e fa tutto lui.