name: Build Gradle project
on:
  push:
    branches:
      - main
      - develop
jobs:
  build-gradle-project:
    runs-on: ${{ matrix.os }}
    
    strategy:
    matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Execute Gradle build on Unix system
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: ./gradlew build
      - name: Execute Gradle build on Windows system
        if: matrix.os == 'windows-latest'
        run: .\gradlew.bat build
        