name: Build Gradle project
on:
  push:
    branches:
      - main
      - develop
jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Execute Gradle build
        run: if ["$RUNNER_OS" == "Linux" || "$RUNNER_OS" == "macOS"]; then
                ./gradlew build
             elif ["$RUNNER_OS" == "Windows" || "$RUNNER_OS" == "macOS"]; then
                .\gradlew.bat build
             else
              echo "$RUNNER_OS not supported"
              exit 1
             fi