name: Deploy Application to AWS EC2 Instance
on:
  push:
    branches:
      - testDeploy

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          PRIVATE_KEY:
            -----BEGIN RSA PRIVATE KEY-----\n
            MIIEogIBAAKCAQEAk4xpAWqNIJmletrtLMZY1ZESuOCjiDLdAYefKgR9nllEDR4V
            YzkMmKbzh6xmYOXrXPEZkq8WvGlazq1zmq+QU/f340jIrun6MyHV/9clB4c2sjpm
            j00e15uCnG/D9htONE7d/WU/yQuAW6L1IGaGGiT0d88sfJ0WEdpTzY9I/3J8itbJ
            4SA9lxAex9V3ou2qPLizOhWcvjtMDbJi8rXZVr2hR/Tv3B3chibxL0QZMaUJr9iV
            YeppGz5Ga5UcO/FvFUg+VWXjYvP5jmmzQFUv3i6iRdG5t7/n7c6GINom4CjB8elz
            1PzrTYJU1FelD2zYknmzDFS6DUzDFdtA5Yj6WwIDAQABAoIBAEq4j7DU6fV5efEW
            j4feRryZBFc2A/sEbyHIMdWQgqE/aZQPCRu/l15zJd8ucoZdyWy++IltO+FcpU0H
            UAUlJb0wVYv3nxHdkgR0/S/cH3eJhSyLIMcvchAUQ/e/LgkjWN5qlkcuEDhbJ7zA
            cMzgvsbcsiU+eLP+xV9zJn9yMbCS3VGCFvqAJolDjrENeFXkTgTJjVsylCEOHyV+
            p62lOfGj8X+D4CjxXdj1QiV5i5D8kPkWnsnUZxBRwkAnRAnxMQdw5gleMUN1JGSF
            fLfqJAD+1HjpAzZ7hc5zHPzDuk/i2DhrQYGRaM/im/VApyfG0Tv7PuQyaB1x8Lah
            TGWzVpkCgYEA5hBgHEnorzSi5/APRt2z5AFcrPpFNjL7gkJ/uP0dBCvtTQzsyI7U
            ZzuSwLdykhGQkOICrhdLxkbRH8h592kuXJd2frv+cus/vuzuvtIAGZgRHEdTFpSP
            77JMLcbmO9vJ+wE4EniT1qicyg/ZXSMX9UWRWMxOs4pHOLQQmmGOf6UCgYEApC6l
            O39L+Shp1grvl9GR5JVY6DcZMnVLfuJY68h/W8ZY/nQ9P1KkyVOIhp79Twt3/4lh
            3TLqOHDm2TnkK0ExZa7uXIiz6a27tlFWyOqmertuAFyKWGIRrUoOp/xGmO0k2zts
            oaFgamJNumgVAV2KlqdnvYSjvyIWQRe0TfVAcf8CgYBSTIFVHUtTgazU85dDboOv
            iJ0yc8TWgp5eFpPCBSmgGGanLXx2skFhPHpe3kDp58ajTXZP+J1urF6a1AhtbP7c
            uIH3DCEV0vnWvsMZF95ZSYC1cP5UEYj74fhGV+R8fT9fvyvjz6ZzH5YW4lyLaMZl
            QyGfdlag+1JHAoL99vAW0QKBgErMGWjGsLT9TWI/LzJKPp4V0CBS4b7UIyXWNs6M
            VEFaVrbt++06WGqEDOHP0vVM80lOrHAavwwhm3oBXsq586gwjtVHTje6d5cy7Uex
            Z1DozM+LWVe0rfr1j0HGs979wtnB89aa75Ln4CN5QYCSvg2ujJuRrwvnmp3jD7io
            b8i/AoGAdJ3RgqATL0SFLxtxsQmEEkuxK96x7Mjqhm8/Xexdh4nQ3pUXQmSMlMjv
            PA/S0iDtUeri4I5763H4wFD2z6fO47vVKHbrS70/Qjq530O7jkuzKGL44wmsKKO1
            2jnY5oAWuRvII7l7QyTXyBSnC1u5lD0lB2jKRdfFAHe/RPsI3os=\n
            -----END RSA PRIVATE KEY-----
          HOSTNAME: ec2-18-185-105-62.eu-central-1.compute.amazonaws.com
          USER_NAME: ubuntu

        run: |
          echo "$PRIVATE_KEY" > ./private_key && chmod 600 ./private_key
          cat ./private_key
          ssh -o StrictHostKeyChecking=no -i ./private_key ${USER_NAME}@${HOSTNAME} '
          
              # Now we have got the access of EC2 and we will start the deploy .
              kubectl delete --all svc
              kubectl delete --all deploy
              kubectl delete --all pods
              sudo docker container delete vue-app
          
              minikube start
              cd my-dashboard/
              
              sudo docker pull leomarzoli/traffic_management_system:latest
              kubectl apply -f intersection-agents-deployment.yaml,intersection-agents-service.yaml,spring-db-app-deployment.yaml,spring-db-app-service.yaml,user-db-deployment.yaml,user-db-service.yaml
              docker run -it --rm -d -p 8080:80 --name vue-app traffic-management-vue-app:latest
              
              minikube tunnel
              '